services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # Only build the api for the development environment
      target: development
    volumes:
      - ./backend:/usr/src/app    
    env_file:
      - ./.env    
    command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always    
    ports:
      - "5432:5432"
    volumes:
      - transcendence-postgres:/var/lib/postgresql/data    
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Only build the api for the development environment
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "8000:3000"
    restart: always
    environment:
      NODE_ENV: development
volumes:
  transcendence-postgres: 
    