services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - avatars:/usr/src/app/uploads
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - transcendence

  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - transcendence
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "9090:3000"
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - transcendence

volumes:
  transcendence-postgres:
  avatars:
networks:
  transcendence:
    driver: bridge
