version: "3.8"

# create a postgres service
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
  backend:
    container_name: nestjs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
  ngrok:
    image: wernight/ngrok
    restart: always
    depends_on:
      - backend
    environment:
      - NGROK_PORT=backend:3000
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_HOSTNAME=${NGROK_HOSTNAME}
    ports:
      - 4040:4040
