version: "3.8"

services:
  database:
    container_name: nestjs-postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/data/postgres
    env_file:
      - ./.env
    environment:
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
