
services:
  transcendence:
    container_name: transcendence_devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspaces/transcendence
    entrypoint: /bin/sh -c 'tail --follow /dev/null'
    volumes:
      # Map host folder to workspace
      - ..:/workspaces/transcendence
      # Allow docker socket to use docker CLI inside devcontainer
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

  postgres:
    container_name: transcendence_dev_postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"

  dbadmin:
    container_name: transcendence_dev_adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  transcendence-postgres:
networks:
  backend:
    driver: bridge
